services:
  socket-proxy:
    build:
      context: .
      dockerfile: docker/socket-proxy.dockerfile
    container_name: homelab-socket-proxy
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
      - /tmp
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - POST=1
      - EVENTS=1
      - PING=1
      - VERSION=1
    mem_limit: ${SOCKET_PROXY_MEM_LIMIT:-32m}
    memswap_limit: ${SOCKET_PROXY_MEMSWAP_LIMIT:-64m}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-net


networks:
  socket-proxy-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_socket-proxy-net
