name: homelab

services:
  postgres:
    build:
      context: .
      dockerfile: docker/db/postgres.dockerfile
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - TZ=${POSTGRES_TZ:-Asia/Karachi}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal-net
      - external-net

  migrate:
    build:
      context: .
      dockerfile: docker/db/dbmate.dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB:-postgres}
    restart: "no"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - DBMATE_MIGRATIONS_DIR=/db/migrations
      - DBMATE_NO_DUMP_SCHEMA=true
    secrets:
      - postgres_password
    volumes:
      - ./db/migrations:/db/migrations
    networks:
      - internal-net
    depends_on:
      postgres:
        condition: service_healthy

  valkey:
    build:
      context: .
      dockerfile: docker/db/valkey.dockerfile
    ports:
      - "${VALKEY_PORT:-6380}:6380"
    restart: unless-stopped
    secrets:
      - valkey_password
    volumes:
      - valkey_data:/data
    networks:
      - internal-net
      - external-net

  nginx:
    build:
      context: .
      dockerfile: docker/server/nginx.dockerfile
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    restart: unless-stopped
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/certs:/etc/nginx/certs:ro
      - ./config/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./config/nginx/htpasswd:/etc/nginx/htpasswd:ro

      - ./html:/usr/share/nginx/html:ro
    networks:
      - internal-net
      - external-net


volumes:
  postgres_data:
  valkey_data:


networks:
  internal-net:
    driver: bridge
    internal: true

  external-net:
    driver: bridge


secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
  valkey_password:
    environment: VALKEY_PASSWORD
