name: homelab

services:

  # DB services
  postgres:
    build:
      context: .
      dockerfile: docker/db/postgres.dockerfile
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - TZ=${POSTGRES_TZ:-Asia/Karachi}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal-net
      - external-net

  # Migration services
  migrate:
    build:
      context: .
      dockerfile: docker/db/dbmate.dockerfile
    restart: "no"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - DBMATE_MIGRATIONS_DIR=/db/migrations
      - DBMATE_NO_DUMP_SCHEMA=true
    secrets:
      - postgres_password
    volumes:
      - ./db/migrations:/db/migrations
    networks:
      - internal-net
    depends_on:
      postgres:
        condition: service_healthy

  # Cache/Broker services
  valkey:
    build:
      context: .
      dockerfile: docker/db/valkey.dockerfile
    ports:
      - "${VALKEY_PORT:-6380}:6380"
    restart: unless-stopped
    secrets:
      - valkey_password
    volumes:
      - valkey_data:/data
    networks:
      - internal-net
      - external-net

  # Web server
  nginx:
    build:
      context: .
      dockerfile: docker/server/nginx.dockerfile
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    restart: unless-stopped
    environment:
      - NGINX_HOST=${NGINX_HOST}
    networks:
      - internal-net
      - external-net
    depends_on:
      paperless:
        condition: service_started
        required: false

  # Utility services
  gotenberg:
    build:
      context: .
      dockerfile: docker/utils/gotenberg.dockerfile
    restart: unless-stopped

  tika:
    build:
      context: .
      dockerfile: docker/utils/apache-tika.dockerfile
    restart: unless-stopped

  # Services
  paperless:
    build:
      context: .
      dockerfile: docker/services/paperless-ngx.dockerfile
    restart: unless-stopped
    environment:
      - PAPERLESS_SECRET_KEY_FILE=/run/secrets/paperless_secret_key
      - PAPERLESS_REDIS_FILE=/run/secrets/valkey_url
      - PAPERLESS_URL=http://paperless.${NGINX_HOST}
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=http://paperless.${NGINX_HOST}:${HTTP_PORT:-80},https://paperless.${NGINX_HOST}:${HTTPS_PORT:-443}
    secrets:
      - paperless_secret_key
      - valkey_url
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - ./paperless/consume:/usr/src/paperless/consume
    networks:
      - internal-net
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      valkey:
        condition: service_healthy
      gotenberg:
        condition: service_started
      tika:
        condition: service_started


volumes:
  postgres_data:
  valkey_data:
  paperless_data:
  paperless_media:


networks:
  internal-net:
    driver: bridge
    internal: true

  external-net:
    driver: bridge


secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
  valkey_password:
    environment: VALKEY_PASSWORD
  valkey_url:
    environment: VALKEY_URL
  paperless_secret_key:
    environment: PAPERLESS_SECRET_KEY
