services:
  authentik:
    build:
      context: .
      dockerfile: docker/authentik.dockerfile
    container_name: homelab-authentik
    restart: unless-stopped
    shm_size: 512mb
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__NAME=authentik_db
      - AUTHENTIK_POSTGRESQL__PASSWORD=authentik
      - AUTHENTIK_POSTGRESQL__USER=authentik_user
      - AUTHENTIK_SECRET_KEY=file:///run/secrets/authentik_secret_key
      - AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED:-false}
      - AUTHENTIK_LOG_LEVEL=${AUTHENTIK_LOG_LEVEL:-debug}
      - AUTHENTIK_WEB__WORKERS=${AUTHENTIK_WEB__WORKERS:-1}
      - AUTHENTIK_WEB__THREADS=${AUTHENTIK_WEB__THREADS:-2}
    secrets:
      - authentik_secret_key
    labels:
      - traefik.enable=true
      - traefik.docker.network=homelab_internal-net
      - traefik.http.routers.authentik.rule=Host(`authentik.${DOMAIN:?base domain is required}`)
      - traefik.http.routers.authentik.entrypoints=web
      - traefik.http.services.authentik.loadbalancer.server.port=9000
    mem_limit: ${AUTHENTIK_WEB__MEM_LIMIT:-768m}
    memswap_limit: ${AUTHENTIK_WEB__MEMSWAP_LIMIT:-1g}
    volumes:
    - ./authentik/data:/data
    - ./authentik/custom-templates:/templates
    networks:
      - postgres-net
      - internal-net

  authentik-worker:
    build:
      context: .
      dockerfile: docker/authentik-worker.dockerfile
    container_name: homelab-authentik-worker
    restart: unless-stopped
    shm_size: 512mb
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__NAME=authentik_db
      - AUTHENTIK_POSTGRESQL__PASSWORD=authentik
      - AUTHENTIK_POSTGRESQL__USER=authentik_user
      - AUTHENTIK_SECRET_KEY=file:///run/secrets/authentik_secret_key
      - AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED:-false}
      - AUTHENTIK_WORKER__PROCESSES=${AUTHENTIK_WORKER__PROCESSES:-1}
      - AUTHENTIK_WORKER__THREADS=${AUTHENTIK_WORKER__THREADS:-2}
    secrets:
      - authentik_secret_key
    mem_limit: ${AUTHENTIK_WORKER__MEM_LIMIT:-768m}
    memswap_limit: ${AUTHENTIK_WORKER__MEMSWAP_LIMIT:-1g}
    volumes:
      - ./authentik/data:/data
      - ./authentik/certs:/certs
      - ./authentik/custom-templates:/templates
    networks:
      - postgres-net
      - internal-net
      - socket-proxy-net

networks:
  postgres-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_postgres-net

  internal-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_internal-net

  socket-proxy-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_socket-proxy-net

secrets:
  authentik_secret_key:
    environment: AUTHENTIK_SECRET_KEY
