port 6380
bind * -::*
protected-mode yes
include /run/secrets/valkey_auth

maxmemory 128mb
maxmemory-policy allkeys-lru

timeout 300
loglevel notice
databases 8

dir /data
appendonly yes
appendfsync everysec
