services:
  paperless:
    build:
      context: .
      dockerfile: docker/paperless-ngx.dockerfile
    restart: unless-stopped
    environment:
      - LANG=en_US.UTF-8
      - PAPERLESS_USERMAP_UID=${UID:-1000}
      - PAPERLESS_USERMAP_GID=${GID:-1000}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE:-eng}
      - PAPERLESS_OCR_LANGUAGES=${PAPERLESS_OCR_LANGUAGES:-deu}

      # Web server config
      - PAPERLESS_SECRET_KEY_FILE=/run/secrets/paperless_secret_key
      - PAPERLESS_REDIS_FILE=/run/secrets/valkey_url
      - PAPERLESS_URL=http://paperless.${NGINX_HOST:?nginx host is required}
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=http://paperless.${NGINX_HOST:?nginx host is required}:${HTTP_PORT:-80},https://paperless.${NGINX_HOST:?nginx host is required}:${HTTPS_PORT:-443}
      - PAPERLESS_USE_X_FORWARD_HOST=true
      - PAPERLESS_USE_X_FORWARD_PORT=true
      - PAPERLESS_PROXY_SSL_HEADER=["HTTP_X_FORWARDED_PROTO", "https"]

      # Tika Config
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998

      # DB Config
      - PAPERLESS_DBENGINE=postgresql
      - PAPERLESS_DBHOST=postgres
      # TODO: pass these credentials securely
      - PAPERLESS_DBNAME=paperless_db
      - PAPERLESS_DBUSER=paperless_user
      - PAPERLESS_DBPASS=paperless
    secrets:
      - paperless_secret_key
      - valkey_url
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - ./data/export:/usr/src/paperless/export
      - ./data/consume:/usr/src/paperless/consume
    networks:
      - postgres-net
      - valkey-net
      - internal-net


volumes:
  paperless_data:
    name: homelab_paperless_data
  paperless_media:
    name: homelab_paperless_media


networks:
  postgres-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_postgres-net

  valkey-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_valkey-net

  internal-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_internal-net


secrets:
  valkey_url:
    environment: VALKEY_URL
  paperless_secret_key:
    environment: PAPERLESS_SECRET_KEY
