services:
  traefik:
    build:
      context: .
      dockerfile: docker/traefik.dockerfile
    container_name: homelab-traefik
    restart: unless-stopped
    command:
      # Docker provider via socket-proxy
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=homelab_internal-net

      # Entrypoints
      - --entrypoints.web.address=:${HTTP_PORT:-80}
      - --entrypoints.websecure.address=:${HTTPS_PORT:-443}

      # Health and logging
      - --ping=true
      - --log.level=INFO
      - --accesslog=true
      - --api.dashboard=true  # Not exposed until a router is set for this

    labels:
      - traefik.enable=true
      - traefik.docker.network=homelab_internal-net

      # Router for dashboard
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN:?base domain is required}`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=dashboard-auth
      - traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USERS:?dashboard credentials are required}
    ports:
      - "${HTTP_PORT:-80}:${HTTP_PORT:-80}"
    security_opt:
      - no-new-privileges:true
    read_only: true
    networks:
      internal-net:
        aliases:
          - authentik.${DOMAIN:?base domain is required}
          - paperless.${DOMAIN:?base domain is required}
      external-net:
      socket-proxy-net:


networks:
  internal-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_internal-net

  external-net:
    driver: bridge
    external: true
    name: homelab_external-net

  socket-proxy-net:
    driver: bridge
    external: true
    internal: true
    name: homelab_socket-proxy-net
