## These settings affect the postgres container and does not affect the host.
## For example: Changing the port setting here changes the container port not the host port.

# listen_addresses = localhost
# port = 5432
# max_connections = 100
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 256MB
effective_io_concurrency = 200
# statement_timeout = 0s   # disabled
# lock_timeout = 0s        # disabled
# deadlock_timeout = 1s
# transaction_timeout = 0s # disabled
